name: Build with artifacts
on: push
jobs:
  build:
    strategy:
      matrix:
        node: [16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v3
        with:
          path: '~/.npm'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build/ # path/to/artifact
