name: Github Actions Demo
# on: [push]
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # - run: echo "triggered by a ${{ github.event_name }} event"
      - uses: actions/checkout@v4
      - name: Starting node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: testing
        run: npm test
      - name: linting
        run: npm run lint