name: Demo Workflow

# on: workflow_dispatch
# on: [ push ]
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    # types: [opened, synchronize, closed]

jobs:
  init:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      # - run: echo "The job was triggered by a ${{ github.event_name }} event"
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # - name: install modules
      #   run: npm ci
      - run: npm ci
      # - name: Test and lint
      #   run: |
      #     npm test
      #     npm run lint
      - run: npm test
      - run: npm run lint

  next-job:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event"
      - run: pwd